version: '3.8'

services:
  geth:
    image: 160885291539.dkr.ecr.eu-north-1.amazonaws.com/go-ethereum:latest
    container_name: geth-node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command:
      - --dev
      - --dev.period 1
      - --http
      - --http.addr 0.0.0.0
      - --http.port 8545
      - --http.api eth,net,web3
      - --http.corsdomain "*"
      - --ws
      - --ws.addr 0.0.0.0
      - --ws.port 8546
      - --ws.api eth,net,web3
      - --ws.origins "*"
