apiVersion: v1
kind: Service
metadata:
  name: go-ethereum-predeployed-service
  namespace: devnet
spec:
  selector:
    app: go-ethereum-predeployed
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8545
    targetPort: 8545
